<!DOCTYPE html>
<html lang="en" class="marketing-document">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ $metaDescription ?? 'ClassM8 helps academies and studios sell classes, manage students, schedule teachers, track attendance and collect payments from one connected platform.' }}">
    <title>{{ $title ?? 'ClassM8' }}</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        :root{--ink:#101828;--muted:#667085;--line:rgba(16,24,40,.11);--blue:#2563eb;--cyan:#06b6d4;--purple:#7c3aed;--pink:#ec4899;--orange:#f97316;--green:#10b981;--yellow:#fbbf24;--soft:#f8fbff;--shadow:0 24px 70px rgba(15,23,42,.10)}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);background:radial-gradient(circle at 8% 3%,rgba(37,99,235,.12),transparent 28%),radial-gradient(circle at 92% 8%,rgba(236,72,153,.10),transparent 27%),linear-gradient(180deg,#fff 0%,#f8fbff 48%,#fff 100%);overflow-x:hidden}a{color:inherit}.page{min-height:100vh}.wrap{width:min(1180px,calc(100% - 40px));margin:0 auto}
        .nav{position:sticky;top:14px;z-index:60;margin-top:14px;padding:13px 16px;display:flex;align-items:center;justify-content:space-between;gap:20px;border:1px solid rgba(255,255,255,.84);border-radius:999px;background:rgba(255,255,255,.88);backdrop-filter:blur(18px);box-shadow:0 12px 35px rgba(15,23,42,.08)}.brand{display:flex;align-items:center;gap:10px;text-decoration:none;font-weight:950;letter-spacing:-.035em}.brand-mark{width:38px;height:38px;border-radius:14px;background:linear-gradient(135deg,var(--blue),var(--cyan),var(--pink));box-shadow:0 12px 30px rgba(37,99,235,.28)}.nav-links{display:flex;align-items:center;gap:20px;font-size:14px;font-weight:800;color:#344054}.nav-links a{text-decoration:none}.nav-links a:hover{color:var(--blue)}
        .btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:46px;padding:12px 20px;border:0;border-radius:999px;text-decoration:none;font-weight:900;transition:.22s ease;cursor:pointer}.btn:hover{transform:translateY(-2px)}.btn-primary{color:#fff;background:linear-gradient(135deg,var(--blue),var(--purple),var(--pink));box-shadow:0 18px 35px rgba(124,58,237,.24)}.btn-soft{color:#1d4ed8;background:#eff6ff;border:1px solid rgba(37,99,235,.14)}.btn-dark{background:#101828;color:#fff}
        .hero{padding:82px 0 58px}.hero-grid{display:grid;grid-template-columns:1.03fr .97fr;gap:42px;align-items:center}.eyebrow{display:inline-flex;align-items:center;gap:9px;padding:9px 14px;border-radius:999px;border:1px solid rgba(37,99,235,.15);background:rgba(255,255,255,.82);box-shadow:0 12px 28px rgba(15,23,42,.07);color:#1d4ed8;font-size:13px;font-weight:900}.dot{width:9px;height:9px;border-radius:999px;background:var(--green);box-shadow:0 0 0 7px rgba(16,185,129,.12)}h1,h2,h3{letter-spacing:-.04em}.hero h1{margin:20px 0 18px;font-size:clamp(44px,6vw,76px);line-height:.98;letter-spacing:-.065em}.gradient{background:linear-gradient(135deg,var(--blue),var(--purple),var(--pink),var(--orange));background-clip:text;-webkit-background-clip:text;color:transparent}.lead{margin:0;color:var(--muted);font-size:19px;line-height:1.75}.actions{display:flex;flex-wrap:wrap;gap:13px;margin-top:28px}.subnav{display:flex;flex-wrap:wrap;gap:10px;margin-top:25px}.pill{padding:9px 13px;border-radius:999px;background:#fff;border:1px solid var(--line);font-size:13px;font-weight:850;color:#475467}
        .photo-stage{position:relative;min-height:520px;border-radius:38px;overflow:hidden;background:#111827;box-shadow:0 34px 80px rgba(15,23,42,.18)}.photo-stage img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.photo-stage:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(15,23,42,.02),rgba(15,23,42,.58))}.photo-caption{position:absolute;z-index:2;left:24px;right:24px;bottom:24px;padding:20px;border-radius:24px;background:rgba(255,255,255,.92);backdrop-filter:blur(16px);box-shadow:0 20px 50px rgba(15,23,42,.22)}.photo-caption strong{display:block;font-size:18px}.photo-caption span{display:block;color:var(--muted);margin-top:5px;line-height:1.5}.floating-card{position:absolute;z-index:3;right:18px;top:18px;min-width:180px;padding:15px 16px;border-radius:20px;background:rgba(16,24,40,.9);color:#fff;box-shadow:0 18px 45px rgba(15,23,42,.3)}.floating-card b{font-size:22px}.floating-card small{display:block;opacity:.72;margin-top:2px}
        .section{padding:72px 0}.section-head{max-width:800px;margin-bottom:34px}.kicker{color:var(--blue);font-size:12px;font-weight:950;letter-spacing:.13em;text-transform:uppercase}.section h2,.page-head h1{margin:10px 0 14px;font-size:clamp(34px,4.7vw,58px);line-height:1.02}.section-copy{margin:0;color:var(--muted);font-size:18px;line-height:1.75}.grid-3{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.grid-2{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.card,.panel{border:1px solid var(--line);background:rgba(255,255,255,.9);box-shadow:var(--shadow)}.card{padding:25px;border-radius:27px}.card-icon{width:46px;height:46px;display:grid;place-items:center;border-radius:16px;background:linear-gradient(135deg,var(--blue),var(--cyan));color:#fff;font-weight:950}.card h3{margin:18px 0 9px;font-size:22px}.card p{margin:0;color:var(--muted);line-height:1.7}.card ul,.check-list{margin:16px 0 0;padding:0;list-style:none;display:grid;gap:10px;color:#475467}.card li,.check-list li{position:relative;padding-left:25px;line-height:1.55}.card li:before,.check-list li:before{content:'✓';position:absolute;left:0;color:var(--green);font-weight:950}
        .feature-showcase{display:grid;grid-template-columns:.9fr 1.1fr;gap:30px;align-items:center}.feature-showcase.reverse{grid-template-columns:1.1fr .9fr}.browser{border-radius:30px;background:#fff;border:1px solid var(--line);box-shadow:0 34px 80px rgba(15,23,42,.14);overflow:hidden}.browser-bar{display:flex;align-items:center;gap:7px;padding:13px 16px;background:#f8fafc;border-bottom:1px solid #e5e7eb}.browser-bar i{width:10px;height:10px;border-radius:999px;background:#cbd5e1}.screen{padding:20px;background:linear-gradient(180deg,#f8fafc,#eef4ff);min-height:330px}.screen-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.screen-title{font-weight:950;font-size:18px}.screen-chip{font-size:11px;font-weight:900;padding:7px 10px;border-radius:999px;background:#dcfce7;color:#166534}.stat-row{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.mini-stat{padding:14px;border-radius:17px;background:#fff;border:1px solid #e5e7eb}.mini-stat strong{display:block;font-size:20px}.mini-stat span{font-size:11px;color:#667085}.class-list{display:grid;gap:10px;margin-top:14px}.class-item{display:grid;grid-template-columns:52px 1fr auto;gap:12px;align-items:center;padding:13px;background:#fff;border-radius:18px;border:1px solid #e5e7eb}.class-date{height:48px;border-radius:14px;background:#eff6ff;display:grid;place-items:center;font-weight:950;color:#1d4ed8;line-height:1}.class-item b{font-size:13px}.class-item small{display:block;color:#667085;margin-top:4px}.status{font-size:10px;font-weight:900;padding:7px 9px;border-radius:999px;background:#f3e8ff;color:#6b21a8}
        .classcard-demo{padding:24px;border-radius:30px;background:linear-gradient(145deg,#111827,#1d4ed8 52%,#7c3aed);color:#fff;box-shadow:0 32px 70px rgba(37,99,235,.26)}.credit-ring{width:120px;height:120px;border-radius:50%;margin:20px auto;display:grid;place-items:center;background:conic-gradient(#67e8f9 0 72%,rgba(255,255,255,.18) 72%);position:relative}.credit-ring:before{content:'';position:absolute;width:86px;height:86px;border-radius:50%;background:#172554}.credit-ring span{position:relative;z-index:1;text-align:center}.credit-ring b{display:block;font-size:26px}.classcard-demo ul{margin:18px 0 0;padding:0;list-style:none;display:grid;gap:9px}.classcard-demo li{padding:11px 13px;border-radius:14px;background:rgba(255,255,255,.1);font-size:13px}
        .role-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.role-card{padding:20px;border-radius:24px;background:#fff;border:1px solid var(--line);box-shadow:0 15px 35px rgba(15,23,42,.07)}.role-card span{font-size:12px;font-weight:900;color:var(--blue)}.role-card h3{margin:8px 0;font-size:20px}.role-card p{font-size:14px;color:var(--muted);line-height:1.6;margin:0}
        .band{padding:34px;border-radius:34px;background:linear-gradient(135deg,#111827,#1d4ed8,#7c3aed);color:#fff}.band p{color:rgba(255,255,255,.78);line-height:1.75}.steps{display:grid;gap:14px}.step{display:grid;grid-template-columns:58px 1fr;gap:16px;padding:21px;border:1px solid var(--line);border-radius:23px;background:#fff}.step-no{width:48px;height:48px;display:grid;place-items:center;border-radius:16px;background:linear-gradient(135deg,var(--blue),var(--purple));color:#fff;font-weight:950}.step h3{margin:2px 0 6px}.step p{margin:0;color:var(--muted);line-height:1.65}
        .page-head{padding:82px 0 44px;max-width:860px}.pricing{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.price-card{position:relative;padding:28px;border-radius:28px;border:1px solid var(--line);background:#fff;box-shadow:0 18px 48px rgba(15,23,42,.08)}.price-card.featured{border:2px solid #7c3aed;transform:translateY(-8px)}.price-card h3{font-size:24px;margin:0}.price{margin:16px 0;font-size:40px;font-weight:950;letter-spacing:-.06em}.price small{font-size:14px;color:var(--muted);letter-spacing:0}.notice{padding:18px 20px;border-radius:20px;background:#fff7ed;border:1px solid #fed7aa;color:#9a3412;line-height:1.65}.faq{display:grid;gap:13px}.faq details{padding:20px 22px;border:1px solid var(--line);border-radius:20px;background:#fff}.faq summary{cursor:pointer;font-weight:900}.faq p{color:var(--muted);line-height:1.7}
        .proof{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.proof-photo{min-height:330px;border-radius:30px;overflow:hidden;position:relative}.proof-photo img{width:100%;height:100%;object-fit:cover;position:absolute;inset:0}.proof-copy{padding:30px;border-radius:30px;background:#fff;border:1px solid var(--line)}.proof-copy h3{font-size:30px;margin:8px 0 12px}.proof-copy p{color:var(--muted);line-height:1.75}
        .cta{padding:72px 0}.cta-box{padding:48px;border-radius:36px;background:linear-gradient(135deg,#111827,#1d4ed8,#7c3aed,#ec4899);color:#fff}.cta-box h2{margin:0 0 12px;font-size:clamp(34px,4.5vw,58px);line-height:1}.cta-box p{max-width:760px;color:rgba(255,255,255,.78);font-size:18px;line-height:1.7}.footer{padding:22px 0 34px}.footer-inner{display:flex;justify-content:space-between;gap:20px;padding-top:24px;border-top:1px solid var(--line);color:var(--muted);font-size:14px}.footer-links{display:flex;flex-wrap:wrap;gap:16px}.footer-links a{text-decoration:none}
        @media(max-width:920px){.hero-grid,.feature-showcase,.feature-showcase.reverse,.proof{grid-template-columns:1fr}.grid-3,.pricing{grid-template-columns:1fr 1fr}.role-strip{grid-template-columns:1fr 1fr}.nav-links{gap:12px}.nav-links>a:not(.btn){display:none}.photo-stage{min-height:440px}}
        @media(max-width:700px){.wrap{width:min(100% - 28px,1180px)}.nav{border-radius:25px}.hero{padding-top:58px}.grid-3,.grid-2,.pricing,.stat-row,.role-strip{grid-template-columns:1fr}.actions{display:grid}.btn{width:100%}.section{padding:54px 0}.price-card.featured{transform:none}.footer-inner{display:grid}.page-head{padding-top:58px}.photo-stage{min-height:390px}.class-item{grid-template-columns:46px 1fr}.class-item .status{grid-column:2}}
    </style>
</head>
<body class="marketing-page">
<div class="page">
    <header class="wrap nav">
        <a href="{{ url('/') }}" class="brand"><span class="brand-mark"></span><span>ClassM8</span></a>
        <nav class="nav-links" aria-label="Main navigation">
            <a href="{{ route('marketing.features') }}">Features</a>
            <a href="{{ route('marketing.solutions') }}">Who it’s for</a>
            <a href="{{ route('marketing.platform') }}">How it works</a>
            <a href="{{ route('marketing.pricing') }}">Pricing</a>
            <a class="btn btn-soft" href="{{ route('login') }}">Login</a>
            <a class="btn btn-primary" href="{{ route('register') }}">Start now</a>
        </nav>
    </header>

    @yield('content')

    <section class="wrap cta">
        <div class="cta-box">
            <div class="kicker" style="color:#bfdbfe">Ready when your classes are</div>
            <h2>Give your team less admin — and your students a better experience.</h2>
            <p>Bring class sales, plans, class cards, schedules, attendance, subscriptions and payments into one connected ClassM8 workspace.</p>
            <div class="actions">
                <a class="btn" style="background:#fff;color:#1d4ed8" href="{{ route('register') }}">Create your studio</a>
                <a class="btn" style="background:rgba(255,255,255,.14);color:#fff;border:1px solid rgba(255,255,255,.28)" href="{{ route('marketing.features') }}">Explore features</a>
            </div>
        </div>
    </section>

    <footer class="wrap footer">
        <div class="footer-inner">
            <div><strong style="color:#101828">ClassM8</strong><br>Class, academy and studio management by Mueble Group.</div>
            <div class="footer-links">
                <a href="{{ route('marketing.features') }}">Features</a><a href="{{ route('marketing.solutions') }}">Solutions</a><a href="{{ route('marketing.platform') }}">How it works</a><a href="{{ route('marketing.security') }}">Security</a><a href="{{ route('marketing.pricing') }}">Pricing</a><a href="{{ route('login') }}">Login</a>
            </div>
        </div>
    </footer>
</div>
</body>
</html>