<?php

return [
    'sections' => [
        'start' => [
            'title' => 'Getting Started',
            'roles' => ['all'],
            'pages' => [
                'getting-started' => [
                    'title' => 'Welcome to Mueble LMS',
                    'summary' => 'Understand the platform, user levels, domains, and the recommended setup order.',
                    'role' => 'All users',
                    'steps' => [
                        'Mueble LMS has two main areas: the central client portal and each studio’s own subdomain.',
                        'The client owner uses the central portal for studio ownership, SaaS billing, invoices, messages, and account security.',
                        'Studio admins use the studio subdomain to manage teachers, students, classes, plans, class cards, payments, notifications, and settings.',
                        'Teachers use the studio subdomain to view assigned classes, schedules, class cards, plans, and mark attendance.',
                        'Students use the studio subdomain to browse the shop, pay, view schedules, attendance, class cards, notifications, and receipts.',
                    ],
                    'tips' => ['Complete studio settings before inviting staff or publishing paid classes.', 'Enable two-factor authentication from Account or Profile settings.'],
                ],
                'registration-login' => [
                    'title' => 'Registration and Login',
                    'summary' => 'Create an institute account, verify access, sign in, and understand where each role is redirected.',
                    'role' => 'All users',
                    'steps' => [
                        'Open the institute registration page and enter the owner, studio, contact, and requested subdomain information.',
                        'Choose an available platform plan and complete any required trial or subscription step.',
                        'Use the central login for the client owner and superadmin areas.',
                        'Use the studio subdomain login for studio admins, teachers, and students.',
                        'After login, the system redirects each role to its own dashboard.',
                        'When 2FA is enabled, enter the six-digit authenticator code or a recovery code after the password step.',
                    ],
                    'tips' => ['Save the exact studio subdomain for staff and students.', 'Do not share owner or superadmin credentials with studio staff.'],
                ],
                'security' => [
                    'title' => 'Account Security and 2FA',
                    'summary' => 'Protect accounts with strong passwords, authenticator codes, recovery codes, and safe sessions.',
                    'role' => 'All users',
                    'steps' => [
                        'Open Account Settings in the client portal or Profile inside the studio application.',
                        'Scan the QR code using Google Authenticator, Microsoft Authenticator, Authy, Bitwarden, or 1Password.',
                        'Enter the generated six-digit code and current password to enable 2FA.',
                        'Store recovery codes somewhere separate from the device used for authentication.',
                        'Regenerate recovery codes if any are exposed or used.',
                        'Disable 2FA only after confirming the current password.',
                    ],
                    'tips' => ['Each recovery code works once.', 'Superadmins can review audit activity, but cannot see passwords or authenticator secrets.'],
                ],
            ],
        ],
        'client' => [
            'title' => 'Client Owner Guide',
            'roles' => ['admin'],
            'pages' => [
                'client-overview' => [
                    'title' => 'Client Portal Overview',
                    'summary' => 'Manage studio ownership, platform billing, invoices, messages, and account information.',
                    'role' => 'Client owner',
                    'steps' => [
                        'Use Overview to check the studio and platform subscription status.',
                        'Use My Studio to confirm the studio name, subdomain, status, and ownership details.',
                        'Use Messages to communicate with the platform superadmin.',
                        'Use Billing & Plan to review the current SaaS plan and available upgrades.',
                        'Use Invoices to review platform subscription payment records.',
                        'Use Account to update owner details, password, and 2FA.',
                    ],
                ],
                'studio-onboarding' => [
                    'title' => 'Studio Onboarding Checklist',
                    'summary' => 'Prepare a new dance studio, gym, tuition centre, or academy for real users.',
                    'role' => 'Client owner / Studio admin',
                    'steps' => [
                        'Confirm the studio subdomain opens correctly and SSL is active.',
                        'Open Studio Settings and set studio name, contact information, currency, timezone, email, and payment providers.',
                        'Add at least one studio admin for operational backup.',
                        'Add teachers before creating classes, because each class requires a teacher.',
                        'Add students manually or prepare the student registration/invitation process.',
                        'Create classes, plans, or class cards based on how the studio sells access.',
                        'Test a complete student checkout using payment test mode.',
                        'Verify payment, fulfilment, attendance, notifications, receipts, scheduler, and queue worker.',
                    ],
                    'tips' => ['Keep Stripe in test mode until the full workflow is verified.', 'Use the deployment health checks before going live.'],
                ],
                'platform-billing' => [
                    'title' => 'Platform Billing and Plans',
                    'summary' => 'Understand the SaaS subscription paid by the studio owner to use Mueble LMS.',
                    'role' => 'Client owner',
                    'steps' => [
                        'Open Billing & Plan from the client portal.',
                        'Review the current plan, billing interval, limits, trial date, and subscription end date.',
                        'Choose an upgrade when more student, teacher, or admin seats are required.',
                        'Complete payment using the configured platform Stripe checkout.',
                        'Review successful payments under Invoices.',
                        'Contact the superadmin through Messages for billing or domain assistance.',
                    ],
                    'tips' => ['Platform billing is separate from student payments inside the studio.', 'Changing the platform plan does not change class subscription prices.'],
                ],
            ],
        ],
        'admin' => [
            'title' => 'Studio Admin Guide',
            'roles' => ['admin'],
            'pages' => [
                'admin-dashboard' => [
                    'title' => 'Admin Dashboard',
                    'summary' => 'Use the studio dashboard to monitor users, classes, payments, and operational activity.',
                    'role' => 'Studio admin',
                    'steps' => [
                        'Review dashboard totals and recent activity after login.',
                        'Use Manage Users for admins, teachers, and students.',
                        'Use Manage Classes for classes, plans, and class cards.',
                        'Use Payments for transaction history and receipts.',
                        'Use Notifications to communicate with users.',
                        'Use Studio Settings for branding, email, currency, timezone, and payment configuration.',
                    ],
                ],
                'manage-admins' => [
                    'title' => 'Add and Manage Studio Admins',
                    'summary' => 'Create additional operational administrators without sharing the owner login.',
                    'role' => 'Studio admin',
                    'steps' => [
                        'Open Manage Users, then Admins.',
                        'Choose Add Admin and enter name, email, password, and required contact details.',
                        'Save the account and provide the studio subdomain login URL.',
                        'Edit an admin when contact or account information changes.',
                        'Remove access when the staff member leaves the organisation.',
                    ],
                    'tips' => ['Keep at least two trusted admins for operational continuity.', 'Admins can manage studio operations, so only assign this role to authorised staff.'],
                ],
                'manage-teachers' => [
                    'title' => 'Add and Manage Teachers',
                    'summary' => 'Create teacher accounts and prepare them for class and attendance duties.',
                    'role' => 'Studio admin',
                    'steps' => [
                        'Open Manage Users, then Teachers.',
                        'Choose Add Teacher and enter the teacher’s name, email, password, and contact details.',
                        'Create or edit classes and select the teacher from the teacher field.',
                        'Ask the teacher to log in through the studio subdomain.',
                        'Confirm the assigned classes appear in My Classes and Schedule.',
                        'Remove or reassign classes before deleting a teacher account.',
                    ],
                ],
                'manage-students' => [
                    'title' => 'Add and Manage Students',
                    'summary' => 'Create student accounts, review access, and support purchases and attendance.',
                    'role' => 'Studio admin',
                    'steps' => [
                        'Open Manage Users, then Students.',
                        'Choose Add Student and enter identity, contact, and login information.',
                        'Provide the studio subdomain login URL.',
                        'Students can purchase classes, plans, and class cards from the Shop.',
                        'Use Payments to verify successful transactions and pending items.',
                        'Use attendance and assignment records to confirm access was granted.',
                    ],
                ],
                'create-classes' => [
                    'title' => 'Create Classes from A to Z',
                    'summary' => 'Create one-time, repeating, and subscription classes with clear scheduling and billing behaviour.',
                    'role' => 'Studio admin',
                    'steps' => [
                        'Open Manage Classes, Classes, then Add Class.',
                        'Enter class name, teacher, description, capacity, venue, and price.',
                        'Choose One-time class for one session and one payment.',
                        'Choose Repeating class for multiple sessions without automatic recurring billing.',
                        'Choose Subscription class when Stripe should charge automatically on a daily, weekly, monthly, or yearly interval.',
                        'Set the first class date, start time, and end time.',
                        'For repeating or subscription classes, choose how often sessions occur and the final session date.',
                        'Review the setup summary before saving.',
                        'For Stripe subscription classes, the selected final session date is sent to Stripe as the automatic cancellation date.',
                        'Open the class list and verify all generated sessions.',
                    ],
                    'tips' => ['Billing frequency and class frequency are separate.', 'A monthly charge can provide weekly classes, while a daily charge can cover daily sessions.', 'Test unusual combinations before publishing.'],
                ],
                'plans' => [
                    'title' => 'Create Membership Plans',
                    'summary' => 'Bundle sessions or access rules into reusable plans for students.',
                    'role' => 'Studio admin',
                    'steps' => [
                        'Open Manage Classes, then Plans.',
                        'Create a plan with name, description, price, validity, and applicable class/session rules.',
                        'Add plan sessions and assign teachers where required.',
                        'Publish the plan so it appears in the student shop.',
                        'After purchase, confirm the student plan assignment and available sessions.',
                        'Teachers can view assigned plan sessions and mark attendance.',
                    ],
                ],
                'class-cards' => [
                    'title' => 'Create and Use Class Cards',
                    'summary' => 'Sell a fixed number of attendances that can be consumed one visit at a time.',
                    'role' => 'Studio admin',
                    'steps' => [
                        'Open Manage Classes, then Class Cards.',
                        'Create a card with name, price, number of uses, validity, and description.',
                        'Publish it in the shop.',
                        'After payment, confirm the card appears under the student’s My Class Cards.',
                        'Teachers or admins mark usage when the student attends.',
                        'The remaining balance decreases after each valid usage.',
                    ],
                ],
                'payments-admin' => [
                    'title' => 'Payments, Stripe, HitPay, and Receipts',
                    'summary' => 'Configure providers, understand statuses, verify webhooks, and support students.',
                    'role' => 'Studio admin',
                    'steps' => [
                        'Open Studio Settings and configure the enabled payment providers.',
                        'For Stripe, set publishable key, secret key, and webhook secret in the server environment.',
                        'Register the studio webhook endpoint for checkout and subscription events.',
                        'A successful payment should update the order and payment to paid, then queue fulfilment.',
                        'If the Stripe webhook is delayed, the checkout return page securely reconciles the Checkout Session.',
                        'Pending means confirmation or fulfilment has not completed yet; inspect the payment, webhook logs, queue, and failed jobs.',
                        'Use Payments to open transaction details and download receipts.',
                        'HitPay renewals are generated by the Laravel scheduler; Stripe renewals are handled by Stripe webhooks.',
                    ],
                    'tips' => ['Keep the scheduler cron and Supervisor queue worker running.', 'Never expose secret keys in browser code or documentation screenshots.'],
                ],
                'notifications-admin' => [
                    'title' => 'Send Notifications',
                    'summary' => 'Create announcements and communicate operational information to studio users.',
                    'role' => 'Studio admin',
                    'steps' => [
                        'Open Notifications.',
                        'Create a notification with a clear title and message.',
                        'Select the intended recipient or audience supported by the form.',
                        'Publish the notification.',
                        'Users can open notifications from the bell or their role menu.',
                        'Edit or remove outdated notifications where permitted.',
                    ],
                ],
                'studio-settings' => [
                    'title' => 'Studio Settings',
                    'summary' => 'Configure the studio identity, business rules, integrations, and payment behaviour.',
                    'role' => 'Studio admin',
                    'steps' => [
                        'Set studio name, contact details, timezone, and currency.',
                        'Configure outgoing email and send a test email.',
                        'Enable the required student payment providers.',
                        'Confirm Stripe and HitPay server credentials are present in the environment.',
                        'Review seat usage and upgrade the platform plan before limits are reached.',
                        'Save settings and test the student-facing shop and checkout.',
                    ],
                ],
            ],
        ],
        'teacher' => [
            'title' => 'Teacher Guide',
            'roles' => ['teacher'],
            'pages' => [
                'teacher-workflow' => [
                    'title' => 'Teacher Daily Workflow',
                    'summary' => 'View teaching assignments, schedules, plans, class cards, and attendance.',
                    'role' => 'Teacher',
                    'steps' => [
                        'Log in using the studio subdomain.',
                        'Review the dashboard and Schedule for upcoming sessions.',
                        'Open My Classes to view class information and session details.',
                        'Open a session attendance page and mark each assigned student appropriately.',
                        'Use My Plans for plan-based sessions and attendance.',
                        'Use Class Cards to review or mark card usage when authorised.',
                        'Review Notifications for studio announcements.',
                    ],
                    'tips' => ['Only mark attendance after confirming the correct session and student.', 'Report missing students or assignments to a studio admin.'],
                ],
                'teacher-attendance' => [
                    'title' => 'Mark Attendance Correctly',
                    'summary' => 'Record attendance for normal classes, plan sessions, and class-card usage.',
                    'role' => 'Teacher',
                    'steps' => [
                        'Open the relevant class or plan session.',
                        'Confirm the date, time, venue, and participant list.',
                        'Mark the student using the available attendance action.',
                        'For class cards, confirm a remaining use exists before consuming one.',
                        'Refresh or reopen the page to verify the status was saved.',
                        'Contact an admin for corrections that cannot be changed from the teacher view.',
                    ],
                ],
            ],
        ],
        'student' => [
            'title' => 'Student Guide',
            'roles' => ['student'],
            'pages' => [
                'student-first-login' => [
                    'title' => 'Student First Login',
                    'summary' => 'Sign in, secure the account, and understand the student dashboard.',
                    'role' => 'Student',
                    'steps' => [
                        'Open the studio subdomain provided by the studio.',
                        'Sign in using the student email and password.',
                        'Open My Profile and update personal details or password if required.',
                        'Enable two-factor authentication for additional security.',
                        'Review the dashboard, schedule, attendance, payments, class cards, and notifications.',
                    ],
                ],
                'student-shop-checkout' => [
                    'title' => 'Buy a Class, Plan, or Class Card',
                    'summary' => 'Use the shop and checkout safely from selection through payment confirmation.',
                    'role' => 'Student',
                    'steps' => [
                        'Open Shop from the top bar.',
                        'Review the item type, price, session date, validity, and subscription information.',
                        'Add the item to the cart.',
                        'Subscription classes must be checked out alone.',
                        'Open the cart, confirm the item and amount, then proceed to checkout.',
                        'Choose an available payment provider and complete payment.',
                        'Return to the success page and wait for payment confirmation.',
                        'Review Payments for paid status and receipt access.',
                        'Review Schedule, plan access, or My Class Cards to confirm fulfilment.',
                    ],
                    'tips' => ['Do not close the payment page before Stripe or HitPay redirects back.', 'Contact the studio with the order reference if a completed payment remains pending.'],
                ],
                'student-subscriptions' => [
                    'title' => 'Subscription Classes',
                    'summary' => 'Understand recurring charges, class schedules, automatic cancellation, and payment status.',
                    'role' => 'Student',
                    'steps' => [
                        'A subscription class charges automatically at the displayed billing interval.',
                        'The class schedule may use a different recurrence interval from billing.',
                        'The initial payment activates the subscription and class access.',
                        'Future Stripe charges are processed automatically and recorded as renewal payments.',
                        'When the class has a final session date, Stripe is scheduled to cancel at the end of that date.',
                        'Failed renewals may place the subscription into past-due status during the configured grace period.',
                        'Review Payments for each successful or pending billing cycle.',
                    ],
                ],
                'student-schedule-attendance' => [
                    'title' => 'Schedule and Attendance',
                    'summary' => 'Review upcoming sessions and confirm recorded attendance.',
                    'role' => 'Student',
                    'steps' => [
                        'Open Schedule to view upcoming assigned sessions.',
                        'Check the date, time, teacher, and venue before attending.',
                        'Open Attendance to review historical attendance records.',
                        'Contact the studio promptly if an attendance record is incorrect.',
                    ],
                ],
                'student-payments' => [
                    'title' => 'Payments and Receipts',
                    'summary' => 'Understand paid, pending, past-due, cancelled, and failed payment states.',
                    'role' => 'Student',
                    'steps' => [
                        'Open Payments from the student menu.',
                        'Paid means the provider confirmed the charge and the system recorded it.',
                        'Pending means provider confirmation, webhook processing, or fulfilment may still be running.',
                        'Past due usually relates to an unpaid subscription renewal.',
                        'Cancelled means the checkout or payment request was cancelled before completion.',
                        'Use the receipt action for paid transactions.',
                        'Provide the payment reference to the studio when requesting support.',
                    ],
                ],
            ],
        ],
        'superadmin' => [
            'title' => 'Superadmin Guide',
            'roles' => ['superadmin'],
            'pages' => [
                'superadmin-platform' => [
                    'title' => 'Superadmin Platform Operations',
                    'summary' => 'Manage studios, platform users, domains, SaaS plans, payments, messages, and audit logs.',
                    'role' => 'Superadmin',
                    'steps' => [
                        'Use Dashboard for platform-wide totals and recent studios.',
                        'Use Studios to review ownership, status, trial dates, plans, and subscription dates.',
                        'Use Platform Users to search users across all roles and studios.',
                        'Use Domains & Routing to review central and studio domain configuration.',
                        'Use SaaS Plans to create and maintain platform subscription tiers and seat limits.',
                        'Use SaaS Payments for studio-to-platform payment records.',
                        'Use Messages to communicate with client owners.',
                        'Use Audit Logs to review authenticated mutation activity across the platform.',
                    ],
                ],
                'audit-logs' => [
                    'title' => 'Audit Logs',
                    'summary' => 'Investigate who changed what, from which studio, route, IP, and response status.',
                    'role' => 'Superadmin only',
                    'steps' => [
                        'Open Audit Logs from the superadmin dashboard or menu.',
                        'Filter by user, email, IP address, event, route, or studio.',
                        'Review the HTTP method, field names, response status, timestamp, and user agent context.',
                        'Use audit data to investigate account, configuration, and operational changes.',
                        'Sensitive values such as passwords, CSRF tokens, 2FA codes, and recovery codes are excluded.',
                    ],
                ],
                'production-operations' => [
                    'title' => 'Production Operations',
                    'summary' => 'Deploy safely and keep scheduler, queue, webhooks, backups, and monitoring healthy.',
                    'role' => 'Superadmin / Server administrator',
                    'steps' => [
                        'Use deployment/install-services.sh once on each new production server.',
                        'Confirm Supervisor reports the Mueble LMS queue worker as RUNNING.',
                        'Confirm /etc/cron.d/mueble-lms runs artisan schedule:run every minute.',
                        'Use deployment/deploy.sh for future releases.',
                        'Run migrations, build assets, cache configuration, and restart workers during deployment.',
                        'Verify Stripe and HitPay webhook endpoints after domain changes.',
                        'Review queue failures, Laravel logs, scheduler output, backups, storage, SSL, and monitoring regularly.',
                    ],
                    'tips' => ['Production should have no local Git modifications.', 'Test restores, not only backups.'],
                ],
            ],
        ],
        'reference' => [
            'title' => 'Reference and Troubleshooting',
            'roles' => ['all'],
            'pages' => [
                'troubleshooting' => [
                    'title' => 'Troubleshooting Checklist',
                    'summary' => 'Diagnose login, payment, fulfilment, scheduler, queue, email, and domain problems.',
                    'role' => 'All roles / Support',
                    'steps' => [
                        'Confirm the user is on the correct central domain or studio subdomain.',
                        'Confirm the account role, studio assignment, and active status.',
                        'For payment issues, inspect the order, payment, provider dashboard, webhook delivery, queue worker, and failed jobs.',
                        'For missing access, confirm the payment is paid and the fulfilment job completed.',
                        'For recurring billing, verify the Stripe subscription, billing interval, cancel-at date, and webhook events.',
                        'For missing sessions, confirm recurrence frequency, first date, until date, and generated class sessions.',
                        'For email issues, send a test email and inspect the mail configuration and logs.',
                        'For deployment issues, check Git status, current commit, migrations, caches, built assets, Supervisor, and cron.',
                    ],
                ],
                'glossary' => [
                    'title' => 'Glossary',
                    'summary' => 'Quick definitions of the main terms used throughout Mueble LMS.',
                    'role' => 'All users',
                    'steps' => [
                        'Client owner: the customer account that owns a studio and manages SaaS billing.',
                        'Studio admin: an operational administrator inside one studio.',
                        'Class session: one dated occurrence of a class.',
                        'Repeating class: multiple generated sessions without automatic recurring billing.',
                        'Subscription class: recurring provider billing connected to generated class sessions.',
                        'Plan: a packaged membership or session offering.',
                        'Class card: a prepaid number of uses.',
                        'Fulfilment: granting the purchased class, plan, or class-card access after payment.',
                        'Webhook: a secure provider-to-application notification about payment or subscription events.',
                        'Queue worker: the background process that completes jobs such as order fulfilment.',
                        'Scheduler: Laravel’s timed command runner triggered every minute by cron.',
                    ],
                ],
            ],
        ],
    ],
];
